# Generated by Django 4.2.1 on 2023-05-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date1', models.DateField()),
                ('date2', models.DateField(blank=True)),
                ('date3', models.DateField(blank=True)),
                ('date4', models.DateField(blank=True)),
                ('course1', models.TextField()),
                ('course2', models.TextField(blank=True)),
                ('course3', models.TextField(blank=True)),
                ('course4', models.TextField(blank=True)),
            ],
        ),
    ]
