# Generated by Django 4.2.1 on 2023-05-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
