# Generated by Django 4.2.1 on 2023-05-20 05:39

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_time', '0005_remove_score_partners_player_tournament_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='partners',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
