# Generated by Django 4.2.1 on 2023-05-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_time', '0007_tournament_organizer_alter_tournament_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='partners',
        ),
    ]
