# Generated by Django 4.2.1 on 2023-05-22 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_time', '0008_remove_score_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tourney_time.tournament'),
        ),
    ]
