# Generated by Django 4.2.1 on 2023-05-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_time', '0009_alter_score_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='round',
            field=models.IntegerField(default=1),
        ),
    ]
