# Generated by Django 4.2.1 on 2023-05-23 21:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourney_time', '0010_score_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='course2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='course3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='course4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='players', through='tourney_time.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
