# Generated by Django 4.2.1 on 2023-05-24 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourney_time', '0011_alter_tournament_course2_alter_tournament_course3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='course',
        ),
        migrations.RemoveField(
            model_name='score',
            name='date',
        ),
    ]
